### PR TITLE
Import NAV modules globally + version select

### PR DESCRIPTION
**Pull request by Koubek**
Added possibility to import NAV in the user session context.
Added functions also search in predefined paths for all NAV versions and
their modules and when multiple presents it let a user choose the desired
one.

### CODE REVIEW

**Comment by waldo1001** [comment]
Wow, this is awesome.  Thanks for solving my issue on the global-import part .. and much more: solving the multiple version issue! :-)

Can I suggest a few things?  Just about naming?
- rename "Get-NavAdminVersions" to "Get-NAVModuleAdminVersions"
- rename "Get-NavToolVersions" to "Get-NAVModuleToolVersions"
- rename "Import-NavModulesGlobally" to "Import-NAVModules" (this means removing my original function and replace it with your version - which makes much more sense :-))
- rename "Select-VersionNoGui" to "Select-NAVModuleVersion"

you see - basically having a prefix "NAVModule".. .

Can I blog about this?  How would you want me to reference you?

**Comment by Koubek** [comment]
Can you do it by yourself or this is something I have to (sorry, don`t know Git and GitHub very well, just trying to work with it). I prefer you change the names using the conventions you consider relevant.

Reference me... I think this is not so important, it`s up to you :)

**Comment by Koubek** [comment]
Also would be nice to have it in ISE, I can imagine having a dropdown field with the list of available versions. I don`t know if it is possible (don`t use ISE much, instead using VS Code and class PS console).

**Comment by waldo1001** [comment]
I will do it!
Thanks again!  Very nice solution!

**Comment by waldo1001** [comment]
@Koubek 
I created an issue: https://github.com/waldo1001/Cloud.Ready.Software.PowerShell/issues/33

To not forget - perfectly possible!

**Pull request merged**
