### PR TITLE
Improved loading of NAV modules.

### PR DESCRIPTION
**Pull request by Koubek**
- NAV modules can be loaded using background jobs.
- Separate NAV module loading into the new module to avoid loading
unnecessary dependencies when running required functions. This can also
speed-up the process.
- NAV versions vs. NAV modules are displayed in the matrix to show which
module is present in which NAV version.
- Added possibility to run UpdateProfile.ps1. This will add background
loader execution into the PS profile so NAV module search will start
automatically whenever a PS session is being opened.

### CODE REVIEW

**Comment by Koubek** [comment]
Hi, please, consider this contribution as a draft or proposal ;) Everything seems to be working correctly but...
I have added next module and don`t know if it fits your ideas. I haven`t created for example **psd1** file. And will be more stuff like this...
Anyway, the background loading actually speed-up whole process, this is fine...

**Comment by waldo1001** [comment]
I'm trying to understand first - I liked the functionality already quite much, so I want to keep on expanding together with you ;-).

First of all: why are you turning it into a separate module? If that is really necessary, I'd call it something like "Cloud.Ready.Software.NAV.ModuleMgt" (as it doesn't do anything else).  

IF it is possible to keep it just in the existing NAV module, I would like to just do that.. .

There is also a conflict - can you update your master with my version, and solve it?

**Comment by Koubek** [comment]
Yes, of course, I will... Anyway, I did not update before for obvious reasons. I wanted to discuss it before any other steps (and please, keep in mind, PowerShell is just my hobby and my experience is very limited so...):
- A separate module seems to be quite logical when considering existing dependencies defined in **Cloud.Ready.Software.NAV**. You are using **RequiredModules** and this means all of them need to be loaded even when running just background loader. You can see the proposal actually does not require any of those features so... Of course, would be logical to add the new module into dependencies of **Cloud.Ready.Software.NAV** module... This was not included in my PR.
- The naming - ok, I am really poor with naming :) And prefer eventually you add your naming habits and best practices before any merge into your master.
- I did not mention it before (in the PR comments) but there is also one more improvement - you can simply add any other NAV module in the future (new releases) in a really easy way. Actually, you do not need any coding, just add one more line with the module definition and you are good to go...

I will solve the conflict probably tonight, maybe later...

**Comment by waldo1001** [comment]
Ok, I understand that it's becoming quite a big modules ;-).  But it is loading quite fast, no? Do we really need to maintain a separate module, just to gain a second?
I already hate myself having separated the NAV, SQL, Windows and PS modules.
Your contributions are actually "pure NAV", so it fits perfectly into the "..NAV"-module, no?
I love this new functionality and how it works - I'm using it daily!  But I would really appreciate it that you reconsider the fact to put it in a separate module.. . :-). 
It's your call - if you decide to put it separately, we put it separately! :-)

**Comment by Koubek** [comment]
This is your project and I will respect your opinion ;) Anyway, you can separate it in the future if really needed.
I will reintegrate it into NAV module this night.

**Comment by Koubek** [comment]
I am going to add one more thing so if you can wait... This one will be really small one utility and has nothing to do with the previous functionality.

**Comment by waldo1001** [comment]
Aight!
Thanks for this!

**Comment by Koubek** [comment]
Ok, I had a while and finished what started yesterday evening. There is a new function that traverses through ActiveDirectory and let you add one or multiple NAV users based on AD users. You can add for example users from one specific AD group (group members) or you can even filter them in the second step.

Maybe it will need some small improvements but generally, it is working as expected. I have tested it internally on our AD infrastructure only. It is possible some scenarios have not considered because of lag AD experience.

**Comment by Koubek** [comment]
Just to comment the current state - I am done with my contributions. If you want you can try them and eventually merge into your master.

**Comment by Koubek** [comment]
@waldo1001 - have you reviewed the modifications? What is your opinion?

**Comment by waldo1001** [comment]
@Koubek something went wrong.  The changes that were actually committed include that .general-folder that you had removed.  Strange .. but I need to revert the commit (if i'm able to .. :()

**Comment by Koubek** [comment]
@waldo1001 This is pretty strange... I can see it neither in my project nor in the PR I did (or at least in the final state of the PR).

**Comment by Koubek** [comment]
@waldo1001 Sorry for the issues caused by the PR I did.

**Comment by waldo1001** [comment]
@Koubek 
I could have done something wrong myself :-).  So no worries.
Can you create a new PR?  Let's try again ..

**Comment by Koubek** [comment]
@waldo1001 No, I can`t. There is nothing to merge, everything seems to be merged (or at least GitHub says there is no change and I can confirm that from my point of view, visually, there is everything in your master as well).

**Comment by waldo1001** [comment]
@Koubek 
Wow .. look at us .. noobs trying to figure out this github thing ;-).

Well - what is your last change so I can check it against my objects?

**Comment by Koubek** [comment]
@waldo1001 Yes, your are right... ;) Try to checkout again the solution from GitHub (to another folder). I have done it right now from your repo and there is everything that I posted to PR. So it looks like everything is as it should be :)

**Comment by waldo1001** [comment]
@Koubek 
I think I know what went wrong.  My side, as expected.
I merged online, but I think I didn't synch offline (thought I did, but apparently not).  I removed my repo, and cloned again, and all seems to be ok now.
Would make sense, in any case ;-).
Sorry for this - and thanks again for the contributions!

**Comment by Koubek** [comment]
@waldo1001 OK, you are welcome. I hope people will enjoy them as well as I do. You can consider it as a thank you for the rest of the functionality published here for us.

**Pull request merged**
