### PR TITLE
A few Pester tests to test the most common usage scenarios for Get-NAVHighestVersionList

### PR DESCRIPTION
**Pull request by jhoek**

### CODE REVIEW

**Comment by waldo1001** [comment]
Never worked with that - thanks!

**Comment by jhoek** [comment]
Warmly recommended! Running your tests is simply a matter of calling "Invoke-Pester" in the folder where your tests live.

**Comment by waldo1001** [comment]
Yes .. just been reading up on this.
Thanks for introducing me! ☺
/waldo

**Comment by waldo1001** [comment]
@jhoek, 
do you know whether it would be a problem that these test-scripts exist in the module as well?  Because the way it's done now, I would upload these scripts to PowerShellGallery, just because they exist in the folder.. .

**Comment by jhoek** [comment]
Ah, I see. Not sure, actually - sorry. I would say - if your .psm1 and/or .psd1 doesn't include the *.Tests.ps1 files, nothing should be broken.

**Comment by jhoek** [comment]
Judging from what WarrenF has to say about it, your tests should live in a folder *outside* of your module, like so:  http://ramblingcookiemonster.github.io/Building-A-PowerShell-Module/ <http://ramblingcookiemonster.github.io/Building-A-PowerShell-Module/>, section Create the Module and Scaffolding Around It.

**Pull request merged**
