### PR TITLE
Optional testing of all clients

### PR DESCRIPTION
**Pull request by bgbak**
This enables optional testing of all clients.
Turn client testing on/off in the settings file.

### CODE REVIEW

**Comment by SorenKlemmensen** [comment]
I like it. No I love it. Nice work.

**Comment by bgbak** [comment]
Thanks.
I settled on using "Start-Process" to open the URL's as this will use the default browser automatically.

**Comment by waldo1001** [comment]
Great idea.  :-)
But I'm slightly changing the way it is done.  
Basically: it is possible to not have to think about the WebServerInstance.Uri .. I want my powershell to come up with that. 
I will also wrap the "Start-Process" in a "Start-NAVWebClient" function, with the options "Web, Phone, Tablet".
And last but not least, to support it from out of the box/scripts, I'm changing the New-NAVEnvironment and Remove-NAVEnvironment to support creating/removing a WebServerInstance.
So .. I'm taking your changes, but changing them a bit.  So I'm not going to merge this pull request, but commit my changes into them .. hope you don't mind ;-).

**Comment by waldo1001** [comment]
This should be it (I hope :-))
https://github.com/waldo1001/Cloud.Ready.Software.PowerShell/commit/467582ce93336e6877959940b832f9dc8f9b264b

thanks again!

**Comment by bgbak** [comment]
That looks great!
I didn't think of the Get-NavWebServerInstance at the time.
This is much more flexible :)

**Pull request closed without merging**
